# Generated by Django 4.1.2 on 2022-10-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solvit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['semester_given']},
        ),
        migrations.AddField(
            model_name='topic',
            name='belonging_course',
            field=models.CharField(help_text='Ingresar nombre del ramo', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='semester_given',
            field=models.IntegerField(default=1, help_text='Ingresar n° del semestre'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_name',
            field=models.CharField(help_text='Ingresar nombre de la materia', max_length=200, null=True),
        ),
    ]
