# Generated by Django 4.1.2 on 2022-10-24 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solvit', '0002_alter_topic_options_topic_belonging_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(help_text='Ingresar nombre del ramo', max_length=200, null=True)),
                ('course_code', models.CharField(help_text='Ingresar código del ramo', max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_given', models.IntegerField(default=1, help_text='Ingresar n° del semestre')),
            ],
        ),
        migrations.AlterField(
            model_name='topic',
            name='belonging_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='solvit.course'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='semester_given',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='solvit.semester'),
        ),
    ]
