# Generated by Django 4.1.2 on 2022-10-25 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solvit', '0004_rename_semester_given_semester_semester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester',
            old_name='semester',
            new_name='semester_num',
        ),
    ]
