# Generated by Django 4.1.2 on 2022-10-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solvit', '0006_course_semester_given'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='semester_num',
            field=models.IntegerField(help_text='Ingresar n° del semestre', null=True),
        ),
    ]
