# Generated by Django 4.1.2 on 2022-10-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solvit', '0008_course_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='slug',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.SlugField(help_text='Ingresar código del ramo', max_length=6, null=True),
        ),
    ]
