# Generated by Django 4.1.2 on 2022-10-25 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solvit', '0010_alter_topic_belonging_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='belonging_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='solvit.course'),
        ),
    ]
