# Generated by Django 4.1.2 on 2022-10-26 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solvit', '0013_alter_topic_belonging_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='belonging_course',
            field=models.CharField(help_text='Ingresar código del ramo', max_length=6, null=True),
        ),
    ]
