# Generated by Django 4.1.2 on 2022-11-11 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solvit', '0017_quesmodel_topic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuesModel',
        ),
    ]
