# Generated by Django 4.1.2 on 2022-11-11 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solvit', '0019_quesmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuesModel',
        ),
    ]
