# Generated by Django 4.1.2 on 2022-11-11 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solvit', '0020_delete_quesmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(max_length=200, null=True)),
                ('belonging_topic', models.CharField(max_length=200, null=True)),
                ('question', models.ImageField(upload_to='uploads')),
            ],
        ),
    ]
