# Generated by Django 4.1.2 on 2022-11-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solvit', '0021_quesmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excercise_name', models.CharField(max_length=200, null=True)),
                ('belonging_topic', models.CharField(max_length=200, null=True)),
                ('excersise', models.ImageField(upload_to='uploads')),
            ],
        ),
        migrations.DeleteModel(
            name='QuesModel',
        ),
    ]
