# Generated by Django 4.1.2 on 2022-11-11 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solvit', '0022_excercises_delete_quesmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Excercises',
        ),
    ]
